name: vero360_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.20.1
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.10
  flutter_secure_storage: ^9.2.4
  qr_flutter: ^4.1.0
  saver_gallery: ^4.0.1
  app_links: ^6.0.0
  permission_handler: ^11.3.1
  mime: ^1.0.5
  http_parser: ^4.0.2

  # Location
  geolocator: ^10.1.0

  # UI / UX
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0

  # Media
  image_picker: ^1.2.0

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.4.1
  firebase_auth_web: ^5.9.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.1

  # WebView support
  webview_flutter: ^4.10.0 
  webview_flutter_android: ^4.3.1
  webview_flutter_wkwebview: ^3.17.0
  webview_windows: ^0.4.0
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_auth_mocks: ^0.14.1

dependency_overrides:
  firebase_storage_web: ^3.6.22

flutter:
  uses-material-design: true

  assets:
    - assets/logo_mark.png
    - assets/veggies.jpg
    - assets/basket.jpg
    - assets/shoes/airforce.jpg
    - assets/shoes/timberland.jpg
    - assets/shoes/converse.jpg
    - assets/shoes/airmax.jpg
    - assets/happy.jpg
    - assets/uber-cabs-1024x576.webp
    - assets/Queens-Tavern-Steak.jpg
    - assets/chat.png
    - assets/veropay.png
    - assets/exchange.png
    - assets/accomodation.webp
    - assets/homecleaning.png
    - assets/hospital.png
    - assets/gym.jpg
    - assets/barber.webp
    - assets/vero_courier.png

